package org.after.sleep.shopping.common.domain;

public class UserB extends BaseDomain {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_b.user_name
     * 创建时间 : 2019-02-09 21:12:10
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_b.password
     * 创建时间 : 2019-02-09 21:12:10
     */
    private String password;

    /**
     * 手机号 -- user_b.mobile_no
     * 创建时间 : 2019-02-09 21:12:10
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_b.email
     * 创建时间 : 2019-02-09 21:12:10
     */
    private String email;

    /**
     * user_b表的操作属性:serialVersionUID
     * 创建时间 : 2019-02-09 21:12:10
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 user_b.user_name的get方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 数据字段 user_b.user_name的set方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 数据字段 user_b.password的get方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public String getPassword() {
        return password;
    }

    /**
     * 数据字段 user_b.password的set方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * 数据字段 user_b.mobile_no的get方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * 数据字段 user_b.mobile_no的set方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * 数据字段 user_b.email的get方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public String getEmail() {
        return email;
    }

    /**
     * 数据字段 user_b.email的set方法
     * 创建时间 : 2019-02-09 21:12:10
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

}